### ISSUE TITLE
dark mode button issue

### ISSUE THREAD

**Issue by LakinduK** [LakinduK/hacktoberfest2021#6]
![image](https://user-images.githubusercontent.com/38062348/135825661-60287dfa-0d39-4597-860b-5992d62a93fc.png)

in the light mode, the button text should be "Dark mode"

**Comment by coder483** [comment]
i can work on this

**Comment by itsPrajapat** [comment]
Could You Please assign it to me
Thanks

**Comment by LakinduK** [comment]
Thanks for the contributions! 🤗
